server:
  port: 15002
  servlet:
    context-path: /consumer
logging:
  config: classpath:logback-spring.xml
  # 将nacos心跳日志打印级别提高
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error
spring:
  application:
    name: neeyoo-consumer
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
sms:
  code:
    register: SMS_REGISTER_CODE::%s
    modifyPassword: SMS_MODIFY_PASSWORD_CODE::%s

# Mybatis
mybatis:
  type-aliases-package: com.neeyoo
  configLocation: classpath:mybatis.xml
  mapper-locations: classpath:mapper/**/*.xml

#  feign 对hystrix的支持
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000