server:
  port: 15000
logging:
  config: classpath:logback-spring.xml
  # 将nacos心跳日志打印级别提高
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error
spring:
  application:
    name: neeyoo-gateway

jwt:
  blacklist:
      key-format: JWT_BLACKLIST::%s #token黑名单 存储key 登陆

#  feign 对hystrix的支持
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000