server:
  port: 15001
  servlet:
    context-path: /auth
logging:
  config: classpath:logback-spring.xml
  # 将nacos心跳日志打印级别提高
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error
spring:
  application:
    name: neeyoo-authority

jwt:
  secret:
    key: your-secret-key-balabalaxiaomoxian #jwt生成密钥 用户登陆token
  token:
    key-format: NEEYOO_TOKEN::%s #token 存储key 用户登陆token
    expire-time: 604800000 # 毫秒单位 token过期时间：7day 604800000
    refresh:
      key-format: NEEYOO_REFRESH_TOKEN::%s #refreshToken 存储key 登陆token
      expire-time: 2592000000 # 毫秒单位 refreshToken过期时间：30day 2592000000
  blacklist:
    key-format: NEEYOO_BLACKLIST::%s #token黑名单 存储key 登陆
    expire-time: 8640000000 # 毫秒单位 过期时间：100day

sms:
  user:
    register: SMS_REGISTER_CODE::%s
    expire-time: 86400000 # 验证码过期时间 5分钟 = 300000

# Mybatis
mybatis:
  type-aliases-package: com.neeyoo
  configLocation: classpath:mybatis.xml
  mapper-locations: classpath:mapper/**/*.xml

#  feign 对hytrix的支持
feign:
  hystrix:
    enabled: true
