server:
  port: 15002
  servlet:
    context-path: /consumer
logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: neeyoo-consumer
  profiles:
    active: local
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

sms:
  code:
    register: SMS_REGISTER_CODE::%s
    modifyPassword: SMS_MODIFY_PASSWORD_CODE::%s

# Mybatis
mybatis:
  type-aliases-package: com.neeyoo
  configLocation: classpath:mybatis.xml
  mapper-locations: classpath:mapper/**/*.xml

#  feign 对hystrix的支持
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

---
spring:
  profiles: local
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/neeyoo?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    tomcat:
      testOnBorrow: true
      validationQuery: SELECT 1
  redis:
    # Redis数据库索引（默认为0）
    database: 3
    # 连接超时时间（毫秒）
    timeout: 60000
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: -1
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
#是否激活 swagger true or false
swagger:
  enable: true
---
